/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import 'frosted-glass';


import {
  MyName as MyName
} from './components/my-name/my-name';

declare global {
  interface HTMLMyNameElement extends MyName, HTMLElement {
  }
  var HTMLMyNameElement: {
    prototype: HTMLMyNameElement;
    new (): HTMLMyNameElement;
  };
  interface HTMLElementTagNameMap {
    "my-name": HTMLMyNameElement;
  }
  interface ElementTagNameMap {
    "my-name": HTMLMyNameElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-name": JSXElements.MyNameAttributes;
    }
  }
  namespace JSXElements {
    export interface MyNameAttributes extends HTMLAttributes {
      
    }
  }
}

