/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  FrostedVanilla as FrostedVanilla
} from './components/frosted-vanilla/frosted-vanilla';

interface HTMLFrostedVanillaElement extends FrostedVanilla, HTMLElement {
}
declare var HTMLFrostedVanillaElement: {
  prototype: HTMLFrostedVanillaElement;
  new (): HTMLFrostedVanillaElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "frosted-vanilla": HTMLFrostedVanillaElement;
  }
  interface ElementTagNameMap {
      "frosted-vanilla": HTMLFrostedVanillaElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "frosted-vanilla": JSXElements.FrostedVanillaAttributes;
      }
  }
  namespace JSXElements {
      export interface FrostedVanillaAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          backgroundSelector?: string,
          blurAmount?: string
      }
  }
}

